Problem: Find out most visited floors and resource_used

WITH MOST_VISTED_FLOOR AS (
SELECT NAME,FLOOR_NO
FROM
(SELECT NAME,FLOOR_NO, RANK() OVER(PARTITION BY NAME ORDER BY COUNT(1)DESC) AS RN 
FROM ENTRIES
GROUP BY NAME, FLOOR_NO)
WHERE RN = 1),

DISTINCT_RESOURCES AS
(SELECT DISTINCT NAME, RESOURCE_NAME
FROM ENTRIES),

DISTINCT_RESOURCE_USED AS
(SELECT NAME,LISTAGG(RESOURCE_NAME,',') WITHIN GROUP(ORDER BY RESOURCE_NAME) AS RESOURCE_USED
FROM DISTINCT_RESOURCES
GROUP BY NAME)

SELECT E.NAME,COUNT(*) AS TOTAL_VISITS, MVF.FLOOR_NO,RU.RESOURCE_USED
FROM ENTRIES E 
INNER JOIN MOST_VISTED_FLOOR MVF
ON E.NAME = MVF.NAME
INNER JOIN DISTINCT_RESOURCE_USED RU
ON E.NAME = RU.NAME
GROUP BY E.NAME, MVF.FLOOR_NO,RU.RESOURCE_USED